apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
  namespace: bank-app
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  JwtSettings__Issuer: "BankAPI"
  JwtSettings__Audience: "BankClients"
  JwtSettings__ExpirationMinutes: "60"
---
apiVersion: v1
kind: Secret
metadata:
  name: bank-secrets
  namespace: bank-app
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};Encrypt=True;TrustServerCertificate=false;"
  JwtSettings__SecretKey: "${JWT_KEY}"
  SA_PASSWORD: "${SA_PASSWORD}"