apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      serviceAccountName: database
      automountServiceAccountToken: false
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bank-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          value: "bankdb"
        volumeMounts:
        - name: pg-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeralStorage: "5Gi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeralStorage: "10Gi"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - bankdb
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - bankdb
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: pg-storage
        persistentVolumeClaim:
          claimName: pg-pvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: bank-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: bank-app
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: bank-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 20Gi
